security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity: { class: App\Entity\User, property: email }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/v1/auth/login$
      stateless: true
      json_login:
        check_path: /api/v1/auth/login   # ⬅︎ même chemin que celui que tu appelles
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api/
      stateless: true
      jwt: ~

  access_control:
    - { path: ^/api/v1/auth/register$, roles: PUBLIC_ACCESS }
    - { path: ^/api/v1/auth/login$, roles: PUBLIC_ACCESS }   # ⬅︎ autorisé sans token
    - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
