# config/services.yaml
parameters: { }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Enregistre automatiquement la plupart des classes de src/
  App\:
    resource: '../src/'
    # (optionnel) tu peux exclure certains répertoires si besoin
    # exclude:
    #   - '../src/Kernel.php'
    #   - '../src/DependencyInjection/'
    #   - '../src/Entity/'
    #   - '../src/Tests/'

  # ✅ Listener qui modifie la payload de /auth/login
  App\EventListener\JWTAuthenticationSuccessListener:
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
      # (optionnel) ajoute une priorité si tu as d'autres listeners sur le même event
      # - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse, priority: 0 }
